name: 'Build Packages'

on:
  workflow_call:
    inputs:
      version:
        type: string
        default: ''
      publish:
        type: boolean
        default: false
      environment:
        type: string
        required: true
    secrets:
      npm-token:
        required: false

jobs:
  build:
    name: 'Build Package'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: https://registry.npmjs.org/

      - name: 'Set Git Config'
        run: |
          git config --global user.email "ciuser@flxbl.io"
          git config --global user.name "ciuser"

      - name: 'Install Dependencies'
        run: npm i

      - name: 'Build Package'
        run: npm run build

      - name: 'Run Unit Tests'
        if: ${{ inputs.publish == true }}
        run: npm run test -- --colors

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: 'Publish Package'
        if: ${{ inputs.publish == true }}
        run: npm publish --tag ${{ inputs.version }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm-token }}