on:
  push:
    branches:
      - main
name: release-please
permissions: {}
jobs:
 release-please:
   outputs: 
    continue: ${{ steps.release.outputs.releases_created }}
   permissions:
     contents: write # to create release commit (google-github-actions/release-please-action)
     packages: write
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     - uses: actions/setup-node@v4
       with:
         node-version: 20


     - uses: pnpm/action-setup@v2
       with:
          version: 8

     - run: pnpm i
     - run: lerna run build
     - run: lerna run test

     - uses: actions/setup-node@v4
       with:
        node-version: 20
        registry-url: https://npm.pkg.github.com/

     - uses: google-github-actions/release-please-action@v4
       id: release
       with:
         token: ${{ secrets.GHA_TOKEN }}
         config-file: release-please-config.json

     - run: |
         cd packages/sfp-cli
         npm publish
       env:
         NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
       if: ${{ steps.release.outputs.releases_created == 'true'}}

 sync-gitea-mirror:
    runs-on: ubuntu-latest
    if: ${{ needs.release-please.outputs.continue == 'true' || github.event_name == 'workflow_dispatch' }}
    environment: stable
    needs:
      - release-please
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: ' https://source.flxbl.io/flxbl/sfp-pro.git'
          GIT_USERNAME: ${{ secrets.GITEA_USERNAME }}
          GIT_PASSWORD: ${{  secrets.GITEA_TOKEN }}
          PUSH_ALL_REFS: false
          GIT_PUSH_ARGS: '--tags --force --prune'