# This pipeline builds the sfp cli plugin
# Needs following secrets
# NPM_TOKEN :  Token to npm.js for dx@scale scope
# DOCKER_USERNAME : Token to username for ghcr.io for publishing docker
# DOCKER_SECRET: Password/Token for ghcr.io for publishing docker
#
# Needs the following env vars
# The repo name (for docker registry) has to be set in each job due to a limitiation with github actions
# as global vars (non secrets) cant be passed down to other jobs


name: 'Release'

on:
   push:
    branches:
      - main
      - feat/docker-test
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'decision records/**'
      - 'demoreel/**'
      - 'prerequisites/**'

   workflow_dispatch:



# Merge to Develop, create builds   
jobs: 
  build:
    name: 'build packages'
    uses: ./.github/workflows/buildPackages.yml
    with:
      version: ${{ github.ref }}
      publish: true
      environment: build
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}


 # On successfull creation of packages,(or even if lerna skips), create docker image
  build-docker:
    name: 'build docker image'
    uses: ./.github/workflows/sfp-build-docker.yml
    with:
      job-environment: 'build-docker'
      suffix-tag: ${{ github.run_id }}
      repo: 'flxbl-io'
      image: 'sfp-rc'
    secrets:
      username: ${{ secrets.DOCKER_USERNAME }}
      token: ${{ secrets.GITHUB_TOKEN }}
    needs: [ build ]
  
  build-docker-lite:
    name: 'build sfp lite docker image'
    uses: ./.github/workflows/sfp-build-docker.yml
    with:
      job-environment: 'build-docker'
      suffix-tag: ${{ github.run_id }}
      repo: 'flxbl-io'
      dockerFileName: 'sfp-lite'
      image: 'sfp-lite-rc'
    secrets:
      username: ${{ secrets.DOCKER_USERNAME }}
      token: ${{ secrets.GITHUB_TOKEN }}
    needs: [ build ]

 #Promotion Stages



  sfp-alpha:
    name: 'sfp alpha'
    uses: ./.github/workflows/promotePackage.yml
    with:
      version: 'alpha'
      pathToPackageJson: 'packages/sfp-cli/package.json'
      environment: sfp-alpha
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
    needs: [ build ]
  
  alpha-docker:
    name: 'promote docker to alpha'
    uses: ./.github/workflows/sfp-promote-docker.yml
    with:
      job-environment: 'sfp-alpha-docker'
      repo: 'flxbl-io'
      new-tag: alpha   
      image: 'sfp-rc'  
    secrets:
      username: ${{ secrets.DOCKER_USERNAME }}
      token: ${{ secrets.GITHUB_TOKEN }}
    needs: [ build-docker ]

  alpha-docker-lite:
    name: 'promote docker lite to alpha'
    uses: ./.github/workflows/sfp-promote-docker.yml
    with:
      job-environment: 'sfp-alpha-docker'
      repo: 'flxbl-io'
      new-tag: alpha   
      image: 'sfp-lite-rc'  
    secrets:
      username: ${{ secrets.DOCKER_USERNAME }}
      token: ${{ secrets.GITHUB_TOKEN }}
    needs: [ build-docker-lite ]


  sfp-beta:
    name: 'sfp beta'
    uses: ./.github/workflows/promotePackage.yml
    with:
      version: 'beta'
      pathToPackageJson: 'packages/sfp-cli/package.json'
      environment: sfp-beta
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
    needs: [ build ]
  
  beta-docker:
    name: 'promote docker to beta'
    uses: ./.github/workflows/sfp-promote-docker.yml
    with:
      job-environment: 'sfp-beta-docker'
      repo: 'flxbl-io'
      new-tag: beta   
      image: 'sfp-lite-rc' 
    secrets:
      username: ${{ secrets.DOCKER_USERNAME }}
      token: ${{ secrets.GITHUB_TOKEN }}
    needs: [ build-docker ]

  beta-docker-lite:
    name: 'promote docker light to beta'
    uses: ./.github/workflows/sfp-promote-docker.yml
    with:
      job-environment: 'sfp-beta-docker'
      repo: 'flxbl-io'
      new-tag: beta   
      image: 'sfp-rc'  
    secrets:
      username: ${{ secrets.DOCKER_USERNAME }}
      token: ${{ secrets.GITHUB_TOKEN }}
    needs: [ build-docker-lite ]
 
 


  sfp-prod:
    name: 'sfp prod'
    uses: ./.github/workflows/promotePackage.yml
    with:
      version: 'latest'
      pathToPackageJson: 'packages/sfp-cli/package.json'
      environment: sfp-prod
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
    needs: [ build ]
  
  prod-docker:
    name: 'copy rc docker to prod'
    uses: ./.github/workflows/sfp-copy-docker.yml
    with:
      job-environment: 'sfp-prod-docker'
    secrets:
      username: ${{ secrets.DOCKER_USERNAME }}
      token: ${{ secrets.GITHUB_TOKEN }}
      signing_secret: ${{ secrets.SIGNING_SECRET }}
      cosign_password:  ${{ secrets.COSIGN_PASSWORD }}
    needs: [ build-docker ]

  prod-docker-lite:
    name: 'copy rc lite docker to prod'
    uses: ./.github/workflows/sfp-copy-docker.yml
    with:
      job-environment: 'sfp-prod-docker'
      image: sfp-lite-rc
      image-as: sfp-lite
    secrets:
      username: ${{ secrets.DOCKER_USERNAME }}
      token: ${{ secrets.GITHUB_TOKEN }}
      signing_secret: ${{ secrets.SIGNING_SECRET }}
      cosign_password:  ${{ secrets.COSIGN_PASSWORD }}
    needs: [ build-docker-lite ]


