on:
  push:
    branches:
      - main
name: release-please
permissions: {}
jobs:
 release-please:
   permissions:
     contents: write # to create release commit (google-github-actions/release-please-action)
     packages: write

   runs-on: ubuntu-latest
   steps:
     - uses: google-github-actions/release-please-action@v4
       id: release
       with:
         token: ${{ secrets.GHA_TOKEN }}
         release-type: node

     - uses: actions/checkout@v4
     - uses: actions/setup-node@v4
       with:
         node-version: 20


     - uses: pnpm/action-setup@v2
       with:
          version: 8

     - run: pnpm i
     - run: pnpm run build

     - uses: actions/setup-node@v4
       with:
        node-version: 20
        registry-url: https://npm.pkg.github.com/

     - run: npm publish
       env:
         NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
       if: ${{ steps.release.outputs.release_created }}