# Unique name for this workflow
name: Validate PR and Run Tests

# Definition when the workflow should run
on:
    workflow_dispatch:
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
            - develop
            - main

# Jobs to be executed
jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: Use Node.js
            uses: actions/setup-node@v3
            with:
              node-version: '18'
              registry-url: 'https://registry.npmjs.org'
          - uses: pnpm/action-setup@v2
            with:
             version: 8

          - name: 'Install Dependencies'
            run: pnpm i              
          - run: npx lerna run build
          - run: npx lerna run test -- --colors

          - name: Upload coverage reports to Codecov
            uses: codecov/codecov-action@v3
            env:
             CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}


