name: Promote Docker Image in ghcr


on:
  workflow_call:
   inputs:
    job-environment:
      type: string
      required: true
    repo:
      type: string
      required: false
    image:
      type: string
      required: false
      default: sfp
    new-tag:
      type: string
      required: true
   secrets:
     username:
        required: true
     token:
        required: true
jobs:

  build:
    name: 'promote docker image'
    environment: ${{ inputs.job-environment }}
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0


    - name: 'Get package version'
      run: |
         echo "PKG_VERSION=$(jq -r ".version" packages/sfp-cli/package.json)" >> $GITHUB_ENV
         RELEASE_NAME=$(jq -r ".release" packages/sfp-cli/package.json)
         RELEASE_NAME_AS_ARRAY=($RELEASE_NAME)
         RELEASE_NAME=$(echo ${RELEASE_NAME_AS_ARRAY[0]} | cut -c1-3)${RELEASE_NAME_AS_ARRAY[1]}
         echo "RELEASE_NAME=release-$RELEASE_NAME"  >> $GITHUB_ENV
         

    - name: 'Re expose secrets'
      run: |
         echo "DOCKER_TOKEN=${{ env.token }}" >> $GITHUB_ENV
         echo "DOCKER_USERNAME=${{ env.username }}" >> $GITHUB_ENV
      env:
         token : ${{ secrets.token }}
         username : ${{ secrets.username }}

    - name: 'Tag Docker'
      uses: ./.github/actions/tagDocker
      with:
         repo: ${{ inputs.repo }}
         image: ${{ inputs.image }}
         existing-tag: ${{ env.PKG_VERSION }}-${{ github.run_id }}
         new-tag: ${{ inputs.new-tag }}
         registry: ghcr.io
         username:  ${{ env.DOCKER_USERNAME }}
         token: ${{ env.DOCKER_TOKEN }}


    - name: 'Tag Docker With Release Info'
      uses: ./.github/actions/tagDocker
      with:
         repo: ${{ inputs.repo }}
         image: ${{ inputs.image }}
         existing-tag: ${{ env.PKG_VERSION }}-${{ github.run_id }}
         new-tag: release-${{ vars.RELEASE_VERSION }}
         registry: ghcr.io
         username:  ${{ env.DOCKER_USERNAME }}
         token: ${{ env.DOCKER_TOKEN }}